##########################################################
##################  所有profile共有的配置  #################
##########################################################

###################  项目启动端口  ###################
server:
  port: 8081

###################  spring配置  ###################
spring:
  mvc:
    static-path-pattern: /static/**
  http:
    converters:
      preferred-json-mapper: fastjson
    multipart:
      max-request-size: 4096MB #最大请求大小
      max-file-size: 4096MB
      enabled: false #最大文件大小
  devtools:
    restart:
      enabled: true #是否开启开发者工具（true/false）
      additional-paths: src/main/java
  datasource:
        url: jdbc:mysql://127.0.0.1:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
        username: root
        password: 123456
        filters: log4j,wall,mergeStat
  batch:
    job:
      enabled: false
    initializer:
      enabled: false
  thymeleaf:
    cache: false

#mybatis相关配置
mybatis-plus:
    mapper-locations: classpath*:com/zq/learn/fileuploader/persistence/**/mapping/*.xml
    typeAliasesPackage: com.zq.learn.fileuploader.persistence.model
    global-config:
      id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
      db-column-underline: false
      refresh-mapper: true
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: true #配置的缓存的全局开关
      lazyLoadingEnabled: true #延时加载的开关
      multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

#批处理任务的线程数配置
batch:
  thread:
    coreSize: 3
    maxSize: 8
  chunkSize: 2000  #批处理块的大小

